# Generated by Django 4.2 on 2026-03-21 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='English word')),
                ('russian', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Russian translation')),
                ('example', models.TextField(blank=True, verbose_name='Example sentence')),
                ('times_shown', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['-created_at'],
            },
        ),
    ]
